### ISSUE TITLE
Missing /app/docker-entrypoint.sh

### ISSUE THREAD

**Issue by once-returner** [Senzing/docker-senzing-poc-utility#8]
Cloned this repo and pulled down the senzing/senzing-base image. Executed a ```docker build``` command on the repo which was successful but executing ```docker run``` on the generated image shows the following error:

```
/app/docker-entrypoint.sh: line 62: /opt/senzing/docker-runs.sentinel: No such file or directory
```

**Comment by docktermj** [comment]
Can you show me the invocation of the docker image you used:  Example:

```console
sudo docker run \
  --interactive \
  --rm \
  --tty \
  --volume ${SENZING_DIR}:/opt/senzing \
  senzing/senzing-poc-utility /bin/bash
```
And what value do you have for ${SENZING_DIR}?

**Comment by jbutcher21** [comment]
This is not an issue for me because this image is interactive.   What would entrypoint.sh do?

Jeff Butcher
Senzing, Chief Architect
jbutcher@senzing.com<mailto:jbutcher@senzing.com>
(702) 205-8424

Follow Senzing on Website<http://www.senzing.com/> | Twitter<https://twitter.com/senzing> | LinkedIn<https://www.linkedin.com/company/senzing-inc/> | Facebook<https://www.facebook.com/senzinginc/>
If you are not an intended recipient of confidential and privileged information in this email, please delete it, notify us immediately at postmaster@senzing.com<mailto:postmaster@senzing.com>, and do not use or disseminate such information.

**Comment by docktermj** [comment]
@once-returner Have we satisfied your concern? If not, please let us know how to improve the experience.  (cc: @jbutcher21)

If we don't hear back in a week, we'll close the issue for you.

**Comment by docktermj** [comment]
Having not heard back in a week,  I'm closing this issue.  If it still an issue please request that it be re-opened or submit a new issue.
